---
- name: 'Zabbix agent installation'
  win_chocolatey:
    name: '{{ win_software }}'
    state: 'present'
  ignore_errors: yes

- name: 'Zabbix agent configure file transfer'
  win_template:
    src: 'zabbix_agentd.win.conf.j2'
    dest: 'C:\ProgramData\zabbix\zabbix_agentd.conf'
  register: config_upgrade
  ignore_errors: yes

- name: Reload zabbix agent service
  win_service:
    name: 'Zabbix Agent'
    state: 'restarted'
  when: config_upgrade|changed
  ignore_errors: yes

- name: Ensure zabbix agent service is enabled and started
  win_service:
    name: 'Zabbix Agent'
    state: started
    start_mode: auto
  ignore_errors: yes

- name: Firewall rule to allow zabbix agent
  win_firewall_rule:
    enable: yes
    state: present
    action: allow
    direction: In
    name: 'Zabbix Agent'
    protocol: 'TCP'
    localport: '{{ zabbix_agent_listenport }}'
